CREATE TABLE CART (
    CART_NUM VARCHAR2(10) PRIMARY KEY,
    M_ID VARCHAR2(20) NOT NULL references MEMBER(ID),
    P_ID VARCHAR2(20) NOT NULL references PRODUCT(P_ID),
    P_IMG VARCHAR2(50),
    P_NAME VARCHAR2(200) NOT NULL,
    P_AMOUNT NUMBER NOT NULL,
    P_COLOR VARCHAR2(20) NOT NULL,
    P_SIZE VARCHAR2(20) NOT NULL,
    P_OPTION VARCHAR2(20),
    P_PRICE NUMBER NOT NULL
);