CREATE SEQUENCE cart_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999;
CREATE TABLE CART (
    CART_NUM VARCHAR2(10) PRIMARY KEY,
    M_ID VARCHAR2(20) NOT NULL references MEMBER(ID),
    P_ID VARCHAR2(20) NOT NULL references PRODUCT(P_ID),
    P_IMG VARCHAR2(50),
    P_NAME VARCHAR2(200) NOT NULL,
    P_AMOUNT NUMBER NOT NULL,
    P_COLOR VARCHAR2(20) NOT NULL,
    P_SIZE VARCHAR2(20) NOT NULL,
    P_OPTION VARCHAR2(20),
    P_PRICE NUMBER NOT NULL
);

CREATE SEQUENCE o_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999;

CREATE SEQUENCE od_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999;

CREATE TABLE ORDER_TBL (
    ORDER_NUM VARCHAR2(10) primary key,
    M_ID VARCHAR2(20) references MEMBER(ID),
    D_NAME VARCHAR2(20),
    D_PHONE VARCHAR2(15),
    D_ZIP VARCHAR2(10),
    D_ADDRESS1 VARCHAR2(50),
    D_ADDRESS2 VARCHAR2(50),
    ORDER_DATE DATE,
    D_DATE DATE,
	D_EMAIL VARCHAR2(50),
	D_STATUS NUMBER
); /*D_는 딜리버리를 뜻합니다.*/
CREATE TABLE ORDER_DETAIL (
    ORDER_DETAIL_NUM VARCHAR2(10) primary key,
    ORDER_NUM VARCHAR2(10) references ORDER_TBL(ORDER_NUM),
    P_ID VARCHAR2(20) references PRODUCT(P_ID),
    P_IMG VARCHAR2(50),
    P_NAME VARCHAR2(200) NOT NULL,
    P_AMOUNT NUMBER NOT NULL,
    P_COLOR VARCHAR2(20) NOT NULL,
    P_SIZE VARCHAR2(20) NOT NULL,
    P_OPTION VARCHAR2(20),
    P_PRICE NUMBER NOT NULL
);
