/*********************** 주문 테이블 *******************************/
DROP TABLE PRODUCT_ORDER;
CREATE SEQUENCE O_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
MAXVALUE 99999; 

CREATE TABLE PRODUCT_ORDER (
    NUM VARCHAR2(10) PRIMARY KEY,
    ID VARCHAR2(20) REFERENCES CUSTOMER(ID) NOT NULL,
    O_DATE DATE NOT NULL
);

/*********************** 주문 상세 테이블 *******************************/
DROP TABLE PRODUCT_ORDER_DETAIL;
CREATE SEQUENCE O_DETAIL_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
MAXVALUE 99999; 

CREATE TABLE PRODUCT_ORDER_DETAIL (
    OD_NUM VARCHAR2(10) PRIMARY KEY,
    O_NUM VARCHAR2(10) REFERENCES PRODUCT_ORDER(NUM) NOT NULL,
    OD_P_ID VARCHAR2(10) REFERENCES PRODUCT(P_ID) NOT NULL,
    OD_IMG VARCHAR2(50),
    OD_ITEMNAME VARCHAR2(200),
    OD_AMOUNT VARCHAR2(100),
    OD_PRICE NUMBER,
    OD_RESULT CHAR(1) NOT NULL
);

/*********************** 배송 정보 테이블 *******************************/
DROP TABLE DELIVERY;

CREATE SEQUENCE DE_NUM_SEQ
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
MAXVALUE 99999; 

CREATE TABLE DELIVERY (
    DE_NUM VARCHAR2(10) PRIMARY KEY,
    OD_NUM VARCHAR2(10) REFERENCES PRODUCT_ORDER_DETAIL(OD_NUM) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    ZIP NUMBER NOT NULL,
    ADDRESS1 VARCHAR2(50) NOT NULL,
    ADDRESS2 VARCHAR2(50) NOT NULL,
    TEL NUMBER,
    PHONE NUMBER,
    EMAIL VARCHAR2(30),
    MESSAGE VARCHAR2(30),
    R_NAME VARCHAR(20) NOT NULL,
    R_ZIP NUMBER NOT NULL,
    R_ADDRESS1 VARCHAR2(50) NOT NULL,
    R_ADDRESS2 VARCHAR2(50) NOT NULL,
    R_TEL NUMBER,
    R_PHONE NUMBER,
    R_EMAIL VARCHAR2(30)
);



